import { DarkModeToggle } from "@/components/DarkModeToggle";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LinkButton from "@/components/LinkButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hr quiz app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white text-black dark:bg-back dark:text-white p-5`}
      >
        <div className="flex flex-col gap-4">
          <div className="flex flex-col items-start gap-3">
            <h1 className="text-2xl font-semibold">Welcome back!</h1>
            <p className="text-tsecondary">
              Do every day. Compete and see your exam score!
            </p>
          </div>
          <nav className="flex items-center gap-3">
            <LinkButton href="/">Home</LinkButton>
            <DarkModeToggle />
          </nav>
        </div>
        <main className="mt-5">{children}</main>
      </body>
    </html>
  );
}
